FROM golang:latest as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o campaign .

######## Start a new stage from scratch #######
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/campaign .
#COPY --from=builder /app/wait_for_postgres.sh
# Command to run the executable
EXPOSE 4000
CMD ["./campaign"]