version: "3.8"
services:

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - backend

  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"

  users:
    restart: always
    build:
      context: ./users/cmd/app
    ports:
      - '4006:4006'
    networks:
      - backend

  redis-db:
    image: redis
    networks:
      - backend

  mongo:
    image: mongo
    container_name: db_users
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/dbs
    networks:
      - backend


  neo4j-db:
    image: neo4j:latest
    container_name: db_neo
    networks:
      - backend
    environment:
      NEO4J_AUTH: neo4j/root
    ports:
      - '7687:7687'
      - '7474:7474'

  campaign:
    restart: always
    build:
      context: ./campaign/cmd/app
    ports:
      - '4000:4000'
    networks:
      - backend


  feedposts:
    restart: always
    build:
      context: ./feedPosts/cmd/app
    ports:
      - '4001:4001'
    networks:
      - backend
    volumes:
      - feed-data:/var/lib/feedposts/data

  messages:
    restart: always
    build:
      context: ./messages/cmd/app
    ports:
      - '4002:4002'
    networks:
      - backend

  userinteraction:
    restart: always
    build:
      context: ./userInteraction/cmd/app
    ports:
      - '4005:4005'
    networks:
      - backend

  storyposts:
    restart: always
    build:
      context: ./storyPosts/cmd/app
    ports:
      - '4004:4004'
    networks:
      - backend
    volumes:
      - story-data:/var/lib/storyposts/data


  xml-db:
      image: existdb/existdb:latest
      ports:
        - 8081:8080
        - 8443:8443
      networks:
        - backend


volumes:
  mongodb:
  story-data:
  feed-data:

networks:
  backend:
    name: nistagram
    driver: bridge
