version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  campaign:
    image: campaign:compose_build
    build:
      context: ./campaign
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

  feedPosts:
    image: feedPosts:compose_build
    build:
      context: ./feedPosts
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

  notificationSettings:
    image: notificationSettings:compose_build
    build:
      context: ./notificationSettings
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

  storyPosts:
    image: storyPosts:compose_build
    build:
      context: ./storyPosts
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

  userInteraction:
    image: userInteraction:compose_build
    build:
      context: ./userInteraction
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

  users:
    image: users:compose_build
    build:
      context: ./users
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8081

networks:
  backend:
    name: nistagram
