version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  campaign:
    image: campaign:compose_build
    build:
      context: ./campaign/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  feedPosts:
    image: feedposts:compose_build
    build:
      context: ./feedPosts/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  messages:
    image: messages:compose_build
    build:
      context: ./messages/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  notificationSettings:
    image: notificationsettings:compose_build
    build:
      context: ./notificationSettings/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  storyPosts:
    image: storyposts:compose_build
    build:
      context: ./storyPosts/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  userInteraction:
    image: userinteraction:compose_build
    build:
      context: ./userInteraction/cmd/app
    networks:
      - backend
    environment:
      PORT: 8080

  users:
    image: users:compose_build
    build:
      context: ./users/cmd/app

    networks:
      - backend
    environment:
      PORT: 8080

networks:
  backend:
    name: nistagram
