version: "3.8"
services:


  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8081:4007
    networks:
      - backend
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  campaign:
    image: campaign:compose_build
    build:
      context: ./campaign/cmd/app
    networks:
      - backend
    environment:
      PORT: 4000

  feedPosts:
    image: feedposts:compose_build
    build:
      context: ./feedPosts/cmd/app
    networks:
      - backend
    environment:
      PORT: 4001

  messages:
    image: messages:compose_build
    build:
      context: ./messages/cmd/app
    networks:
      - backend
    environment:
      PORT: 4002

  notificationSettings:
    image: notificationsettings:compose_build
    build:
      context: ./notificationSettings/cmd/app
    networks:
      - backend
    environment:
      PORT: 4003

  storyPosts:
    image: storyposts:compose_build
    build:
      context: ./storyPosts/cmd/app
    networks:
      - backend
    environment:
      PORT: 4004

  userInteraction:
    image: userinteraction:compose_build
    build:
      context: ./userInteraction/cmd/app
    networks:
      - backend
    environment:
      PORT: 4005

  users:
    image: users:compose_build
    build:
      context: ./users/cmd/app

    networks:
      - backend
    environment:
      PORT: 4006

networks:
  backend:
    name: nistagram
    driver: bridge
