version: "3.8"
services:

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - backend

  users:
    restart: always
    build:
      context: ./users/cmd/app
    ports:
      - '4006:4006'
    networks:
      - backend

  mongo:
    image: mongo
    container_name: db_users
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/dbs
    networks:
      - backend

  campaign:
    restart: always
    build:
      context: ./campaign/cmd/app
    ports:
      - '4000:4000'
    networks:
      - backend


  feedposts:
    restart: always
    build:
      context: ./feedPosts/cmd/app
    ports:
      - '4001:4001'
    networks:
      - backend

  messages:
    restart: always
    build:
      context: ./messages/cmd/app
    ports:
      - '4002:4002'
    networks:
      - backend

  notificationsettings:
    restart: always
    build:
      context: ./notificationSettings/cmd/app
    ports:
      - '4003:4003'
    networks:
      - backend

  storyposts:
    restart: always
    build:
      context: ./storyPosts/cmd/app
    ports:
      - '4004:4004'
    networks:
      - backend

  userinteraction:
    restart: always
    build:
      context: ./userInteraction/cmd/app
    ports:
      - '4005:4005'
    networks:
      - backend

volumes:
  mongodb:

networks:
  backend:
    name: nistagram
    driver: bridge
